image: node:latest

stages:
  - test

test:
  script:
    - npm install
    - npm run build
    - npm run test
    - npx nyc --reporter cobertura mocha
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
